# Generated by Django 3.2.16 on 2023-01-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Nurse'), (3, 'Surgen')], null=True),
        ),
    ]
