# Generated by Django 3.2.16 on 2023-01-25 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_readinggroup_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='date_finale',
            field=models.DateTimeField(default=3, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
