# Generated by Django 3.2.17 on 2023-02-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230125_2218'),
        ('base', '0005_localization_zipcode'),
    ]

    operations = [
    ]
