# Generated by Django 3.2.17 on 2023-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_merge_20230212_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='date_finale',
            field=models.DateTimeField(null=True),
        ),
    ]
